# Generated by Django 4.1.6 on 2023-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_and_answers',
            name='Split_content',
        ),
        migrations.AddField(
            model_name='questions_and_answers',
            name='audio',
            field=models.TextField(default=''),
        ),
    ]
