# Generated by Django 4.1.6 on 2023-04-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_questions_and_answers_is_mcq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_and_answers',
            name='audioName',
            field=models.TextField(default=''),
        ),
    ]
