# Generated by Django 4.1.6 on 2023-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_questions_and_answers_audioname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
    ]
