# Generated by Django 4.1.6 on 2023-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Banner',
            field=models.TextField(default=None),
        ),
    ]
