# Generated by Django 4.1.6 on 2023-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Banner',
            field=models.TextField(default=''),
        ),
    ]
