# Generated by Django 4.1.6 on 2023-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_alter_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=15),
        ),
    ]
