# Generated by Django 4.1.6 on 2023-05-11 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_test_result_specific_solution_fib'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams_collection',
            name='Last_Modified_Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
