# Generated by Django 4.1.6 on 2023-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_exams_collection_last_modified_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams_collection',
            name='Last_Modified_Date_Time',
            field=models.DateTimeField(default='2023-05-11 14:47:36.444333'),
        ),
    ]
